volumes:
  conf-vol:
    name: ${CONF_VOL_NAME}
    driver: ${VOL_DRIVER}
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTS}
      device: ${CONF_VOL_DEVICE:-:/cmak-conf-vol/}
