version: '3.5'

services:
  kafka-manager:
    image: ${IMAGE_NAME:-giabar/gb-kafkamanager}:${IMAGE_TAG:-latest}
    environment:
      ZK_HOSTS: zk-1:${ZK_PORT},zk-2:${ZK_PORT},zk-3:${ZK_PORT}
      KM_ARGS: '-Djava.net.preferIPv4Stack=true'
    networks:
      kafka-net:
      traefik-net:
    healthcheck:
      test: wget --spider -S -t 3 http://localhost:${KM_PORT}
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-10s}
      retries: ${HEALTHCHECK_RETRIES:-3}
      start_period: ${HEALTHCHECK_START_PERIOD:-2m}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      labels:
        traefik.docker.network: traefik-net
        traefik.frontend.auth.basic.users: ${UI_AUTH}
        traefik.frontend.rule: Host:kafkamanager.${PUBLIC_HOSTNAME}
        traefik.backend: kafka-manager
        traefik.port: "${KM_PORT}"
      restart_policy:
        delay: ${RESTART_DELAY:-30s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-512M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-320M}

networks:
  kafka-net:
    name: ${KAFKA_NET_NAME:-kafka-net}
    driver: ${KAFKA_NET_DRIVER:-overlay}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true
