version: '3.5'

services:
  cmak:
    image: ${IMAGE_NAME:-hlebalbau/kafka-manager}:${IMAGE_TAG:-stable}
    command:
      - -Dhttp.port=${HTTP_PORT}
      - -Djava.net.preferIPv4Stack=true
    environment:
      ZK_HOSTS:
      APPLICATION_SECRET:
      KAFKA_MANAGER_AUTH_ENABLED:
      KAFKA_MANAGER_USERNAME:
      KAFKA_MANAGER_PASSWORD:
    networks:
      kafka-net:
      traefik-net:
    volumes:
      - conf-vol:/kafka-manager/conf
    healthcheck:
      test: wget --spider -nv -t 1 http://localhost:${HTTP_PORT}/api/health
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-10s}
      retries: ${HEALTHCHECK_RETRIES:-3}
      start_period: ${HEALTHCHECK_START_PERIOD:-2m}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      labels:
        traefik.frontend.rule: Host:${TRAEFIK_SUBDOMAIN:-kafkamanager}.${PUBLIC_HOSTNAME}
        traefik.backend: cmak
        traefik.port: '${HTTP_PORT}'
      restart_policy:
        delay: ${RESTART_DELAY:-30s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-512M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-320M}

networks:
  kafka-net:
    name: ${KAFKA_NET_NAME:-kafka-net}
    driver: ${KAFKA_NET_DRIVER:-overlay}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true

volumes:
  conf-vol:
    name: ${CONF_VOL_NAME:-cmak-conf-vol}
    driver: local
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTIONS}
      device: :/cmak-conf-vol/
